import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { AddOnService } from 'src/add-on-service/entities/add-on-service.entity';
import { Invoice } from 'src/invoice/entities/invoice.entity';
import { Member } from 'src/member/entities/member.entity';
import { Subscription } from 'src/subscription/entities/subscription.entity';
import { SubscriptionType } from 'src/subscription/enums/subcription.enum';
import { Repository } from 'typeorm';

@Injectable()
export class SeederService {
  constructor(
    @InjectRepository(Member)
    private memberRepository: Repository<Member>,
    @InjectRepository(Subscription)
    private subscriptionRepository: Repository<Subscription>,
    @InjectRepository(AddOnService)
    private addOnServiceRepository: Repository<AddOnService>,
    @InjectRepository(Invoice)
    private invoiceRepository: Repository<Invoice>,
  ) {}

  /**
   * Seed the database with initial data.
   *
   * @return {Promise<void>} A promise that resolves when the database is seeded successfully.
   */
  async seed() {
    await this.clearDatabase();

    const members = [
      { firstName: 'Chinedu', lastName: 'Okafor', email: 'user1@yopmail.com' },
      { firstName: 'Aisha', lastName: 'Abubakar', email: 'user2@yopmail.com' },
      { firstName: 'Femi', lastName: 'Adeyemi', email: 'user3@yopmail.com' },
      { firstName: 'Nneka', lastName: 'Nwosu', email: 'user4@yopmail.com' },
      { firstName: 'Olusegun', lastName: 'Adebayo', email: 'user5@yopmail.com' },
      { firstName: 'Zainab', lastName: 'Yusuf', email: 'user6@yopmail.com' },
      { firstName: 'Ifeanyi', lastName: 'Eze', email: 'user7@yopmail.com' },
      { firstName: 'Hauwa', lastName: 'Mohammed', email: 'user8@yopmail.com' },
      { firstName: 'Chiamaka', lastName: 'Nwankwo', email: 'user9@yopmail.com' },
      { firstName: 'Ibrahim', lastName: 'Suleiman', email: 'user10@yopmail.com' },
      { firstName: 'Yetunde', lastName: 'Akinwale', email: 'user11@yopmail.com' },
      { firstName: 'Emeka', lastName: 'Okonkwo', email: 'user12@yopmail.com' },
      { firstName: 'Funmi', lastName: 'Ayodele', email: 'user13@yopmail.com' },
      { firstName: 'Musa', lastName: 'Danjuma', email: 'user14@yopmail.com' },
      { firstName: 'Kelechi', lastName: 'Ogu', email: 'user15@yopmail.com' },
      { firstName: 'Halima', lastName: 'Bello', email: 'user16@yopmail.com' },
      { firstName: 'Obinna', lastName: 'Nwachukwu', email: 'user17@yopmail.com' },
      { firstName: 'Adebisi', lastName: 'Alade', email: 'user18@yopmail.com' },
      { firstName: 'Adaeze', lastName: 'Eze', email: 'user19@yopmail.com' },
      { firstName: 'Sulaiman', lastName: 'Abubakar', email: 'user20@yopmail.com' },
      { firstName: 'Amaka', lastName: 'Chukwu', email: 'user21@yopmail.com' },
      { firstName: 'Chigozie', lastName: 'Umeh', email: 'user22@yopmail.com' },
      { firstName: 'Yemi', lastName: 'Adedoyin', email: 'user23@yopmail.com' },
      { firstName: 'Chinwe', lastName: 'Onwubiko', email: 'user24@yopmail.com' },
      { firstName: 'Aminu', lastName: 'Garba', email: 'user25@yopmail.com' },
      { firstName: 'Ifunanya', lastName: 'Obinna', email: 'user26@yopmail.com' },
      { firstName: 'Tunde', lastName: 'Ajayi', email: 'user27@yopmail.com' },
      { firstName: 'Ngozi', lastName: 'Anozie', email: 'user28@yopmail.com' },
      { firstName: 'Ebuka', lastName: 'Okeke', email: 'user29@yopmail.com' },
      { firstName: 'Mariam', lastName: 'Lawal', email: 'user30@yopmail.com' },
      { firstName: 'Nnamdi', lastName: 'Kalu', email: 'user31@yopmail.com' },
      { firstName: 'Rahmat', lastName: 'Suleiman', email: 'user32@yopmail.com' },
      { firstName: 'Tochukwu', lastName: 'Egbuna', email: 'user33@yopmail.com' },
      { firstName: 'Temidayo', lastName: 'Afolabi', email: 'user34@yopmail.com' },
      { firstName: 'Bolaji', lastName: 'Ogundipe', email: 'user35@yopmail.com' },
      { firstName: 'Latifat', lastName: 'Mustapha', email: 'user36@yopmail.com' },
      { firstName: 'Chukwuma', lastName: 'Obinna', email: 'user37@yopmail.com' },
      { firstName: 'Kudirat', lastName: 'Olamide', email: 'user38@yopmail.com' },
      { firstName: 'Ekene', lastName: 'Anyanwu', email: 'user39@yopmail.com' },
      { firstName: 'Modupe', lastName: 'Adebayo', email: 'user40@yopmail.com' },
    ] as Partial<Member>[];

    const savedMembers = await this.memberRepository.save(members);

    const subscriptions = [
      {
        member: savedMembers[0],
        type: SubscriptionType.ANNUAL_BASIC,
        startDate: new Date('2024-01-01'),
        dueDate: new Date('2025-01-01'),
        totalAmount: 500,
        isFirstMonth: true,
      },
      {
        member: savedMembers[1],
        type: SubscriptionType.MONTHLY_PREMIUM,
        startDate: new Date('2024-03-15'),
        dueDate: new Date('2024-04-15'),
        totalAmount: 50,
        isFirstMonth: true,
      },
      {
        member: savedMembers[2],
        type: SubscriptionType.ANNUAL_PREMIUM,
        startDate: new Date('2024-05-01'),
        dueDate: new Date('2025-05-01'),
        totalAmount: 800,
        isFirstMonth: true,
      },
      {
        member: savedMembers[3],
        type: SubscriptionType.MONTHLY_BASIC,
        startDate: new Date('2024-06-01'),
        dueDate: new Date('2024-07-01'),
        totalAmount: 30,
        isFirstMonth: false,
      },
      {
        member: savedMembers[4],
        type: SubscriptionType.ANNUAL_BASIC,
        startDate: new Date('2024-07-15'),
        dueDate: new Date('2025-07-15'),
        totalAmount: 500,
        isFirstMonth: true,
      },
      {
        member: savedMembers[5],
        type: SubscriptionType.MONTHLY_PREMIUM,
        startDate: new Date('2024-08-01'),
        dueDate: new Date('2024-06-21'),
        totalAmount: 50,
        isFirstMonth: false,
      },
      {
        member: savedMembers[6],
        type: SubscriptionType.ANNUAL_BASIC,
        startDate: new Date('2024-02-10'),
        dueDate: new Date('2025-02-10'),
        totalAmount: 500,
        isFirstMonth: true,
      },
      {
        member: savedMembers[7],
        type: SubscriptionType.MONTHLY_PREMIUM,
        startDate: new Date('2024-03-20'),
        dueDate: new Date('2024-06-20'),
        totalAmount: 50,
        isFirstMonth: false,
      },
      {
        member: savedMembers[8],
        type: SubscriptionType.ANNUAL_PREMIUM,
        startDate: new Date('2024-09-15'),
        dueDate: new Date('2025-09-15'),
        totalAmount: 800,
        isFirstMonth: false,
      },
      {
        member: savedMembers[9],
        type: SubscriptionType.MONTHLY_BASIC,
        startDate: new Date('2024-04-05'),
        dueDate: new Date('2024-06-18'),
        totalAmount: 30,
        isFirstMonth: false,
      },
      {
        member: savedMembers[10],
        type: SubscriptionType.ANNUAL_BASIC,
        startDate: new Date('2024-07-22'),
        dueDate: new Date('2025-07-22'),
        totalAmount: 500,
        isFirstMonth: false,
      },
      {
        member: savedMembers[11],
        type: SubscriptionType.MONTHLY_PREMIUM,
        startDate: new Date('2024-08-15'),
        dueDate: new Date('2024-09-15'),
        totalAmount: 50,
        isFirstMonth: false,
      },
      {
        member: savedMembers[12],
        type: SubscriptionType.ANNUAL_PREMIUM,
        startDate: new Date('2024-10-01'),
        dueDate: new Date('2025-10-01'),
        totalAmount: 800,
        isFirstMonth: true,
      },
      {
        member: savedMembers[13],
        type: SubscriptionType.MONTHLY_BASIC,
        startDate: new Date('2024-01-10'),
        dueDate: new Date('2024-02-10'),
        totalAmount: 30,
        isFirstMonth: false,
      },
      {
        member: savedMembers[14],
        type: SubscriptionType.ANNUAL_BASIC,
        startDate: new Date('2024-03-01'),
        dueDate: new Date('2025-03-01'),
        totalAmount: 500,
        isFirstMonth: true,
      },
      {
        member: savedMembers[15],
        type: SubscriptionType.MONTHLY_PREMIUM,
        startDate: new Date('2024-05-01'),
        dueDate: new Date('2024-06-01'),
        totalAmount: 50,
        isFirstMonth: false,
      },
      {
        member: savedMembers[16],
        type: SubscriptionType.ANNUAL_PREMIUM,
        startDate: new Date('2024-07-01'),
        dueDate: new Date('2025-07-01'),
        totalAmount: 800,
        isFirstMonth: true,
      },
      {
        member: savedMembers[17],
        type: SubscriptionType.MONTHLY_BASIC,
        startDate: new Date('2024-02-15'),
        dueDate: new Date('2024-06-18'),
        totalAmount: 30,
        isFirstMonth: false,
      },
      {
        member: savedMembers[18],
        type: SubscriptionType.ANNUAL_BASIC,
        startDate: new Date('2024-06-10'),
        dueDate: new Date('2025-06-10'),
        totalAmount: 500,
        isFirstMonth: true,
      },
      {
        member: savedMembers[19],
        type: SubscriptionType.MONTHLY_PREMIUM,
        startDate: new Date('2024-09-01'),
        dueDate: new Date('2024-06-17'),
        totalAmount: 50,
        isFirstMonth: false,
      },
      {
        member: savedMembers[20],
        type: SubscriptionType.ANNUAL_BASIC,
        startDate: new Date('2024-01-15'),
        dueDate: new Date('2025-01-15'),
        totalAmount: 500,
        isFirstMonth: true,
      },
      {
        member: savedMembers[21],
        type: SubscriptionType.MONTHLY_PREMIUM,
        startDate: new Date('2024-04-01'),
        dueDate: new Date('2024-05-01'),
        totalAmount: 50,
        isFirstMonth: true,
      },
      {
        member: savedMembers[22],
        type: SubscriptionType.ANNUAL_PREMIUM,
        startDate: new Date('2024-11-01'),
        dueDate: new Date('2025-11-01'),
        totalAmount: 800,
        isFirstMonth: true,
      },
      {
        member: savedMembers[23],
        type: SubscriptionType.MONTHLY_BASIC,
        startDate: new Date('2024-05-10'),
        dueDate: new Date('2024-06-10'),
        totalAmount: 30,
        isFirstMonth: false,
      },
      {
        member: savedMembers[24],
        type: SubscriptionType.ANNUAL_BASIC,
        startDate: new Date('2024-02-05'),
        dueDate: new Date('2025-02-05'),
        totalAmount: 500,
        isFirstMonth: true,
      },
      {
        member: savedMembers[25],
        type: SubscriptionType.MONTHLY_PREMIUM,
        startDate: new Date('2024-03-25'),
        dueDate: new Date('2024-04-25'),
        totalAmount: 50,
        isFirstMonth: false,
      },
      {
        member: savedMembers[26],
        type: SubscriptionType.ANNUAL_PREMIUM,
        startDate: new Date('2024-08-01'),
        dueDate: new Date('2025-08-01'),
        totalAmount: 800,
        isFirstMonth: true,
      },
      {
        member: savedMembers[27],
        type: SubscriptionType.MONTHLY_BASIC,
        startDate: new Date('2024-09-20'),
        dueDate: new Date('2024-10-20'),
        totalAmount: 30,
        isFirstMonth: false,
      },
      {
        member: savedMembers[28],
        type: SubscriptionType.ANNUAL_BASIC,
        startDate: new Date('2024-03-10'),
        dueDate: new Date('2025-03-10'),
        totalAmount: 500,
        isFirstMonth: true,
      },
      {
        member: savedMembers[29],
        type: SubscriptionType.MONTHLY_PREMIUM,
        startDate: new Date('2024-10-01'),
        dueDate: new Date('2024-11-01'),
        totalAmount: 50,
        isFirstMonth: false,
      },
      {
        member: savedMembers[30],
        type: SubscriptionType.ANNUAL_PREMIUM,
        startDate: new Date('2024-06-01'),
        dueDate: new Date('2025-06-01'),
        totalAmount: 800,
        isFirstMonth: false,
      },
      {
        member: savedMembers[31],
        type: SubscriptionType.MONTHLY_BASIC,
        startDate: new Date('2024-02-10'),
        dueDate: new Date('2024-03-10'),
        totalAmount: 30,
        isFirstMonth: false,
      },
      {
        member: savedMembers[32],
        type: SubscriptionType.ANNUAL_BASIC,
        startDate: new Date('2024-07-01'),
        dueDate: new Date('2025-07-01'),
        totalAmount: 500,
        isFirstMonth: false,
      },
      {
        member: savedMembers[33],
        type: SubscriptionType.MONTHLY_PREMIUM,
        startDate: new Date('2024-08-10'),
        dueDate: new Date('2024-09-10'),
        totalAmount: 50,
        isFirstMonth: false,
      },
      {
        member: savedMembers[34],
        type: SubscriptionType.ANNUAL_BASIC,
        startDate: new Date('2024-01-20'),
        dueDate: new Date('2025-01-20'),
        totalAmount: 500,
        isFirstMonth: true,
      },
      {
        member: savedMembers[35],
        type: SubscriptionType.MONTHLY_PREMIUM,
        startDate: new Date('2024-04-01'),
        dueDate: new Date('2024-05-01'),
        totalAmount: 50,
        isFirstMonth: false,
      },
      {
        member: savedMembers[36],
        type: SubscriptionType.ANNUAL_PREMIUM,
        startDate: new Date('2024-05-15'),
        dueDate: new Date('2025-05-15'),
        totalAmount: 800,
        isFirstMonth: true,
      },
      {
        member: savedMembers[37],
        type: SubscriptionType.MONTHLY_BASIC,
        startDate: new Date('2024-06-01'),
        dueDate: new Date('2024-07-01'),
        totalAmount: 30,
        isFirstMonth: true,
      },
      {
        member: savedMembers[38],
        type: SubscriptionType.ANNUAL_BASIC,
        startDate: new Date('2024-08-01'),
        dueDate: new Date('2025-08-01'),
        totalAmount: 500,
        isFirstMonth: true,
      },
      {
        member: savedMembers[39],
        type: SubscriptionType.MONTHLY_PREMIUM,
        startDate: new Date('2024-09-10'),
        dueDate: new Date('2024-10-10'),
        totalAmount: 50,
        isFirstMonth: true,
      },
    ] as Partial<Subscription>[];

    const savedSubscriptions = await this.subscriptionRepository.save(subscriptions);

    const invoices = [
      {
        serviceName: 'Monthly Basic Fee',
        amount: 30,
        dueDate: new Date('2024-02-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice1',
        subscription: savedSubscriptions[0],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 500,
        dueDate: new Date('2025-01-15'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice2',
        subscription: savedSubscriptions[1],
      },
      {
        serviceName: 'Monthly Basic Fee',
        amount: 30,
        dueDate: new Date('2024-03-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice3',
        subscription: savedSubscriptions[2],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 500,
        dueDate: new Date('2025-04-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice4',
        subscription: savedSubscriptions[3],
      },
      {
        serviceName: 'Monthly Premium Fee',
        amount: 50,
        dueDate: new Date('2024-04-15'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice5',
        subscription: savedSubscriptions[1],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 500,
        dueDate: new Date('2025-01-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice6',
        subscription: savedSubscriptions[4],
      },
      {
        serviceName: 'First Month Add-On: Personal Training',
        amount: 100,
        dueDate: new Date('2024-02-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice7',
        subscription: savedSubscriptions[4],
      },
      {
        serviceName: 'Monthly Premium Fee',
        amount: 50,
        dueDate: new Date('2024-04-15'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice8',
        subscription: savedSubscriptions[5],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 500,
        dueDate: new Date('2025-07-22'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice9',
        subscription: savedSubscriptions[10],
      },
      {
        serviceName: 'Monthly Premium Fee',
        amount: 50,
        dueDate: new Date('2024-09-15'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice10',
        subscription: savedSubscriptions[11],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 800,
        dueDate: new Date('2025-10-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice11',
        subscription: savedSubscriptions[12],
      },
      {
        serviceName: 'Monthly Basic Fee',
        amount: 30,
        dueDate: new Date('2024-02-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice12',
        subscription: savedSubscriptions[13],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 500,
        dueDate: new Date('2025-02-15'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice13',
        subscription: savedSubscriptions[14],
      },
      {
        serviceName: 'Monthly Basic Fee',
        amount: 30,
        dueDate: new Date('2024-03-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice14',
        subscription: savedSubscriptions[15],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 500,
        dueDate: new Date('2025-04-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice15',
        subscription: savedSubscriptions[16],
      },
      {
        serviceName: 'Monthly Premium Fee',
        amount: 50,
        dueDate: new Date('2024-04-15'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice16',
        subscription: savedSubscriptions[17],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 500,
        dueDate: new Date('2025-01-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice17',
        subscription: savedSubscriptions[18],
      },
      {
        serviceName: 'First Month Add-On: Personal Training',
        amount: 100,
        dueDate: new Date('2024-02-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice18',
        subscription: savedSubscriptions[19],
      },
      {
        serviceName: 'Monthly Premium Fee',
        amount: 50,
        dueDate: new Date('2024-04-15'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice19',
        subscription: savedSubscriptions[20],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 500,
        dueDate: new Date('2025-07-22'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice20',
        subscription: savedSubscriptions[21],
      },
      {
        serviceName: 'Monthly Premium Fee',
        amount: 50,
        dueDate: new Date('2024-09-15'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice21',
        subscription: savedSubscriptions[22],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 800,
        dueDate: new Date('2025-10-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice22',
        subscription: savedSubscriptions[23],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 500,
        dueDate: new Date('2025-02-05'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice17',
        subscription: savedSubscriptions[24],
      },
      {
        serviceName: 'Monthly Premium Fee',
        amount: 50,
        dueDate: new Date('2024-04-25'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice17',

        subscription: savedSubscriptions[25],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 800,
        dueDate: new Date('2025-08-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice17',

        subscription: savedSubscriptions[26],
      },
      {
        serviceName: 'Monthly Basic Fee',
        amount: 30,
        dueDate: new Date('2024-10-20'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice17',

        subscription: savedSubscriptions[27],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 500,
        dueDate: new Date('2025-03-10'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice17',

        subscription: savedSubscriptions[28],
      },
      {
        serviceName: 'Monthly Premium Fee',
        amount: 50,
        dueDate: new Date('2024-11-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice17',

        subscription: savedSubscriptions[29],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 800,
        dueDate: new Date('2025-06-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice17',

        subscription: savedSubscriptions[30],
      },
      {
        serviceName: 'Monthly Basic Fee',
        amount: 30,
        dueDate: new Date('2024-03-10'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice17',

        subscription: savedSubscriptions[31],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 500,
        dueDate: new Date('2025-07-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice17',

        subscription: savedSubscriptions[32],
      },
      {
        serviceName: 'Monthly Premium Fee',
        amount: 50,
        dueDate: new Date('2024-09-10'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice17',

        subscription: savedSubscriptions[33],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 500,
        dueDate: new Date('2025-01-20'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice17',

        subscription: savedSubscriptions[34],
      },
      {
        serviceName: 'Monthly Premium Fee',
        amount: 50,
        dueDate: new Date('2024-05-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice17',

        subscription: savedSubscriptions[35],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 800,
        dueDate: new Date('2025-05-15'),
        invoiceDate: new Date(),
        subscription: savedSubscriptions[36],
      },
      {
        serviceName: 'Monthly Basic Fee',
        amount: 30,
        dueDate: new Date('2024-07-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice20',

        subscription: savedSubscriptions[37],
      },
      {
        serviceName: 'Annual Membership Fee',
        amount: 500,
        dueDate: new Date('2025-08-01'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice28',

        subscription: savedSubscriptions[38],
      },
      {
        serviceName: 'Monthly Premium Fee',
        amount: 50,
        dueDate: new Date('2024-10-10'),
        invoiceDate: new Date(),
        link: 'http://example.com/invoice27',

        subscription: savedSubscriptions[39],
      },
    ];

    await this.invoiceRepository.save(invoices);

    const addOnServices = [
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[0], dueDate: new Date('2024-02-01') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[1], dueDate: new Date('2024-04-15') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[4], dueDate: new Date('2024-02-01') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[5], dueDate: new Date('2024-04-15') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[10], dueDate: new Date('2024-09-15') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[11], dueDate: new Date('2025-10-01') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[12], dueDate: new Date('2025-02-10') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[13], dueDate: new Date('2025-03-01') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[14], dueDate: new Date('2024-06-01') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[15], dueDate: new Date('2025-07-01') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[16], dueDate: new Date('2024-03-15') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[17], dueDate: new Date('2025-06-10') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[18], dueDate: new Date('2024-10-01') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[19], dueDate: new Date('2025-01-15') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[20], dueDate: new Date('2024-05-01') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[21], dueDate: new Date('2025-11-01') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[22], dueDate: new Date('2024-06-10') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[23], dueDate: new Date('2025-02-05') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[24], dueDate: new Date('2024-04-25') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[25], dueDate: new Date('2025-08-01') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[26], dueDate: new Date('2024-10-20') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[27], dueDate: new Date('2025-03-10') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[28], dueDate: new Date('2024-11-01') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[29], dueDate: new Date('2025-06-01') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[30], dueDate: new Date('2024-03-10') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[31], dueDate: new Date('2025-07-01') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[32], dueDate: new Date('2024-09-10') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[33], dueDate: new Date('2025-01-20') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[34], dueDate: new Date('2024-05-01') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[35], dueDate: new Date('2025-05-15') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[36], dueDate: new Date('2024-07-01') },
      { name: 'Towel Rental', monthlyAmount: 20, subscription: savedSubscriptions[37], dueDate: new Date('2025-08-01') },
      { name: 'Personal Training', monthlyAmount: 100, subscription: savedSubscriptions[38], dueDate: new Date('2024-10-10') },
    ] as Partial<AddOnService>[];
    await this.addOnServiceRepository.save(addOnServices);

    console.log('Database seeded successfully');
  }
  /**
   * Clears the entire database by truncating the "subscription", "member", "add_on_service", and "invoice" tables.
   *
   * @return {Promise<void>} A promise that resolves when the database has been cleared.
   */
  async clearDatabase() {
    await Promise.all([
      this.subscriptionRepository.query('TRUNCATE TABLE "subscription" CASCADE;'),
      this.memberRepository.query('TRUNCATE TABLE "member" CASCADE;'),
      this.addOnServiceRepository.query('TRUNCATE TABLE "add_on_service" CASCADE;'),
      this.invoiceRepository.query('TRUNCATE TABLE invoice CASCADE;'),
    ]);
  }
}
